### ISSUE TITLE
Feature: User can view and click through a carousel on the home page

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/ajax-project#1]
## ⚙️ Feature

User can view and click through a carousel on the home page

## 📐 Functionality

User can click through a carousel of 3 different views on the home page, each with a unique image and text. The carousel can be clicked through using the arrows on either side, or the circles at the bottom. The carousel will automatically cycle through the views every 5 seconds. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/110089434/202050760-498d4b59-8db6-4170-8f57-01bb0dfa9cb7.png)

## ✅ Task List

- [x] Create a view option that displays upon the initial opening of the application. 
- [x] Create a navbar with links to the home, recipe, feed, post, and contact us views. 
- [x] Create a carousel with three alternating views, each with unique text and images that match the wireframes above. 
- [x] Structure the layout in HTML, the functionality in JavaScript, and the visual appeal in CSS.
- [x] Update CSS to incorporate a responsible layout for both desktop and mobile views.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
