### ISSUE TITLE
Feature: User can view and click on beer recipes from a provided “thumbnail” list

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/ajax-project#2]
## ⚙️ Feature

User can view and click on beer recipes from a provided “thumbnail” list

## 📐 Functionality

The user will be able to view a list of 24 different "thumbnails", organized into four rows of six columns. The "thumbnails" will show an image and the name of a beer, and each "thumbnail" will serve as a link to a new view where the details of that recipe will be shown. 

## 🖼️ Wireframes

![Recipes Screenshot](https://user-images.githubusercontent.com/110089434/201786926-a03b7b65-2af5-4524-bacf-a018efd4059b.png)
![Recipes 2 Screenshot](https://user-images.githubusercontent.com/110089434/201786930-5a0e3b52-1c4a-4ccb-b6be-1a1617e1a2ea.png)

## ✅ Task List

- [x] Create a new view with the title "Recipes". 
- [x] Create a layout of four rows and six columns, with each "box" containing a "thumbnail", comprised of an image and the name of a beer. 
- [x] Make each "thumbnail" a clickable link that leads to a new view with all the details of the specific recipe that was clicked on. 
- [x] Update the "Recipes" link in the navbar to always bring the user back to the "thumbnail" list page. 
- [x] Ensure the "thumbnails" fall into two columns when changed to a mobile device view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
