### ISSUE TITLE
Feature: User can filter beer recipes by IBU or ABV

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/ajax-project#3]
## ⚙️ Feature

User can filter beer recipes by IBU or ABV.

## 📐 Functionality

The user can select an ABV or IBU value from dropdown menu, which will filter the "thumbnails" to only show beer recipes that meet the specified qualifications. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/110089434/201793166-2e9b47c6-b4c4-4fe8-9d02-bba7a5019106.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a form to the second column-half of the "Recipes" text on the Recipes page.
- [x] In this form, include a label and two `<select>` elements, each with 4 options. Include a pre-selected option with no value.
- [x] Use CSS to format the form so that it visually matches the Figma wireframes above. 
- [x] Write a new function with a condition that checks if either select element has a value. If it does, delete the rendered thumbnails. Include another condition that iterates through the recipes array of object and only renders thumbnails that pass the condition specified by the value of the select element. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
