### ISSUE TITLE
Feature: User can post and view entries of their own brew batches

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/ajax-project#4]
## ⚙️ Feature

User can post and view entries of their own brew batches

## 📐 Functionality

The user can create a post with a picture of the brew batch they want to share and view it in the "Posts" section.

## 🖼️ Wireframes

![New Post Screenshot](https://user-images.githubusercontent.com/110089434/201793617-ea0dee08-db04-499b-b6e7-f2e2a22df2cd.png)
![Posts Screenshot](https://user-images.githubusercontent.com/110089434/201793621-c305237b-6948-4003-833f-30e0dc440a11.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new view option with a data-view value of "new-post-page".
- [x] Include HTML and CSS to create the white box of the "New Post" page. 
- [x] Create a new object in the data.js file and assign it the following properties and values:
  - [x] view: 'new-post-page',
  - [x] posts: [], 
  - [x] editing: null,
  - [x] nextPostId: 1
- [x] Use a form with <input> and <textarea> elements so the user can enter a title, text, and upload an image. Make all inputs "required".
- [x] Listen for 'input' events on the file upload <input> to update the src attribute of the photo preview when the input value changes.
- [x] Listen for 'submit' events on the journal entry form and:
   - [x] Put the form's input values into a new object.
   - [x] Add the nextPostId to the object.
   - [x] Increment the nextPostId on the data model.
   - [x] Prepend the new object to the posts in the data model.
   - [x] Reset the image preview's `src' attribute.
   - [x] Reset the form inputs.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new entry receives an incrementing postId.
- [x] Add a sibling div[data-view="posts-page"] to the HTML.
- [x] Add an empty unordered list to the div[data-view="posts-page"] element in the HTML.
- [x] Add some dummy posts to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the posts list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single post object and returns a DOM tree that matches one of the example posts in the HTML.
- [x] Use a loop to create a DOM tree for each post in the data model and append it to the page when the 'DOMContentLoaded' event is fired.
- [x] Remove the example HTML posts once the user's posts are successfully being appended to the DOM on page load.
- [x] Ensure that submitting a post also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new post automatically shows the 'post-page' view without reloading the page.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
