### ISSUE TITLE
Feature: User can edit and delete their entries

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/ajax-project#5]
## ⚙️ Feature

User can edit and delete their entries

## 📐 Functionality

The user can edit and delete the entries they have posted previously. This will be done by clicking on the "edit" icon. When this icon is clicked, will will pre-populate a variation of the "New Post" page and change views for the user. 

## 🖼️ Wireframes

![Edit Post Screenshot](https://user-images.githubusercontent.com/110089434/201794749-a7f59e13-ee72-4c74-bef3-306c2156143c.png)
![Edit Icon Screenshot](https://user-images.githubusercontent.com/110089434/201794752-49590452-fd96-4041-928d-94b6bfa3eacf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Listen for clicks on the parent element of all rendered entries.
- [x] Show the entry form if an edit icon was clicked.
- [x] Find the matching entry object in the data model and assign it to the data model's editing property if an edit icon was clicked.
- [x] Pre-populate the entry form with the clicked entry's values from the object found in the data model.
- [x] Update the entry form's submit handler function to conditionally add a new entry object or update the existing one.
- [x] Update the entry form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] Make the trash can icon a link to a new view.
- [x] Show a confirmation modal when the user clicks the Delete Entry click target.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [x] Show the Posts list if the user clicks Delete.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
